fix math expression
qulacs/qulacs-rtd pull request #47
Opened 2022-10-05 11:55 UTC by herring101

数式の表示が崩れていたため、修正しました。[これ](http://docs.qulacs.org/ja/latest/intro/4.2_cpp_tutorial.html)など

やったこと

## 
```
:raw-latex:`\f`\ :math:`数式\f`
```
となっていたのをすべて
```
:math:`数式`
```
に置き換えました。

##
pythonチュートリアルだけなぜかmdファイルだったため、[pandoc](https://pandoc.org/)を用いてrstファイルに変換しました。

##
英語のドキュメントの数式も一部おかしかったので修正しました。

2022-10-05 23:45 UTC, forest1040 approved these changes
ありがとうございます！
丁度、気になってました！！

2022-10-06 06:53 UTC, Hiroya-W requested changes
ありがとうございます！
手元で試してみて、1箇所だけスタイルが崩れてしまっていたので、そこだけ修正お願いします

2022-10-06 06:53 UTC, Hiroya-W commented on ja/source/intro/4.1_python_tutorial.rst
> + :math:`2^n` 次元でなければなりません。
`:math:`の部分が改行されていると、インライン数式にならないっぽいのですね
改行しないか、改行位置を修正しておくと良いと思います

```suggestion
2量子ビット以上の大きさのゲートを作るには、一つ目の引数に対象となる添え字のリストを、二つ目に行列を与えます。n量子ビットゲートを作るとき、
行列の大きさは :math:`2^n` 次元でなければなりません。
```

2022-10-11 01:02 UTC, KowerKoint requested changes
ありがとうございます
数式表現周りでこの他におかしかったのは、
- http://docs.qulacs.org/en/latest/guide/2.0_python_advanced.html#Gate-sum (英語版AdvancedのGate_Sumの項目)のところ($$のすぐ内側に空白を入れてはいけない)
- http://docs.qulacs.org/ja/latest/guide/2.0_python_advanced.html#id29 (日本語版Advancedの状態反射の項目)のところ(数式表現を使っていない)

がありました。
全体を見てると他にも改行周りで箇条書きや見出しなどの表示が崩れてるところがいくつかあったので、別のPRで直したいです。

2022-10-11 01:07 UTC, KowerKoint commented
https://github.com/qulacs/qulacs-rtd/issues/51

2022-10-11 02:36 UTC, KowerKoint commented
- http://docs.qulacs.org/en/latest/guide/2.0_python_advanced.html#Pauli-operator の`$n$`(余計な空白)
 
もありました。ipynbのほうは見てなかったかもしれませんが、数式周りなのでまとめてお願いします。

2022-10-11 09:19 UTC, herring101 commented on ja/source/intro/4.1_python_tutorial.rst
> + :math:`2^n` 次元でなければなりません。
修正しました！
自分の手元ではインライン数式になっていたので気づきませんでした...
ありがとうございます。

2022-10-11 09:21 UTC, herring101 commented
指摘していただいた問題点３つ修正しました！
ありがとうございます。
@KowerKoint

2022-10-12 08:04 UTC, KowerKoint approved these changes
手元でビルドして正しく表示されることを確認しました。
ありがとうございます

2022-10-13 05:38 UTC, Hiroya-W approved these changes
LGTMです！

2022-10-14 09:34 UTC, merged