#37 tutorial NoisyEvolution
qulacs/qulacs-rtd pull request #48
Opened 2022-10-06 04:51 UTC by forest1040

NoisyEvolutionとNoisyEvolution_fastのチュートリアルを追加しました。

2022-10-06 07:17 UTC, Hiroya-W requested changes
チュートリアルの追加、ありがとうございます！
reStructuredtextのスタイル周りでいくつかコメントを書きました。確認よろしくおねがいします

2022-10-06 07:17 UTC, Hiroya-W commented on ja/source/guide/2.0_python_advanced.rst
> +NoisyEvolution_fastを使用することを推奨します。
説明の内容は良さそうです。このようなスタイルにしてみるのはどうでしょうか？

```suggestion
環境から相互作用を受け、時間発展によって減衰させるゲートとして、NoisyEvolutionとNoisyEvolution_fastがあります。
これらは、以下の手順で利用できます。

#. 環境から相互作用を受けるシステムをハミルトニアンとして設定し、相互作用の演算子を指定します。
#. 時間発展させる値と微小変化させる時間を指定します。
#. 微分方程式を解く

   - NoisyEvolutionはルンゲクッタ法を使用して、微分方程式を解きます。
   - NoisyEvolution_fastは行列を抜き出して対角化で求めます。

NoisyEvolution_fastは微小変化させる時間の指定は不要で、処理も高速であることから、NoisyEvolution_fastを使用することを推奨します。
```

2022-10-06 07:17 UTC, Hiroya-W commented on ja/source/guide/2.0_python_advanced.rst
> +   from qulacs import QuantumState, Observable, GeneralQuantumOperator
改行が必要です

```suggestion
.. code:: python

   from qulacs import QuantumState, Observable, GeneralQuantumOperator
```

2022-10-06 07:17 UTC, Hiroya-W commented on ja/source/guide/2.0_python_advanced.rst
> +   [0] exp: 0.0
こちらも、改行が必要です

```suggestion
::

   [0] exp: 0.0
```

2022-10-06 07:33 UTC, forest1040 commented
確認ありがとうございます！修正しました。

2022-10-06 07:37 UTC, Hiroya-W approved these changes
ありがとうございます！LGTMです！

2022-10-11 01:30 UTC, KowerKoint reviewed
追加ありがとうございます。
内容に関してではないのですがいくつか細かい指摘をさせていただきました。

2022-10-11 01:30 UTC, KowerKoint commented on ja/source/guide/2.0_python_advanced.rst
> +   observable.add_operator(1, "X 0")
```suggestion
   observable.add_operator(1., "X 0")
```

とても細かいのですが、int -> floatの暗黙的型変換を避けようとしてる気持ちが他の部分では見られるのでここも`1.`に統一したほうが良さそうです。

2022-10-11 01:30 UTC, KowerKoint commented on ja/source/guide/2.0_python_advanced.rst
> +   time = 2
```suggestion
   time = 2.
```
同

2022-10-11 01:30 UTC, KowerKoint commented on ja/source/guide/2.0_python_advanced.rst
> +#. 時間発展させる値と微小変化させる時間を指定します。
```suggestion
#. 環境から相互作用を受けるシステムをハミルトニアンとして設定し、相互作用の演算子を指定する
#. 時間発展させる値と微小変化させる時間を指定する
```
箇条書き内の文体を揃えます

2022-10-11 02:03 UTC, forest1040 commented
ありがとうございます！反映しました。

2022-10-11 03:12 UTC, KowerKoint approved these changes

2022-10-11 11:51 UTC, herring101 approved these changes

2022-10-13 07:52 UTC, kotamanegi approved these changes
LGTM:+1:

2022-10-13 10:01 UTC, merged