Tutorial GeneralQuantumOperator
qulacs/qulacs-rtd pull request #64
Opened 2022-10-12 11:00 UTC by herring101

`GeneralQuantumOperator`に関係するチュートリアルを追加しました。
以下のメソッドについて書き足しました。
- is_hermitian
- apply_to_state

`qulacs-rtd`にはなく`qulacs-osaka`の方にだけ書かれていた、基底状態や`apply_to_state`に関するドキュメントも関係していたのでrstに書き直して追加しました。
https://github.com/Qulacs-Osaka/qulacs-osaka/commit/c138e90e5e1f8280c83fbddbbd32e8181a545025

2022-10-13 00:40 UTC, forest1040 approved these changes
ありがとうございます！

2022-10-13 07:30 UTC, Hiroya-W requested changes
チュートリアル追加ありがとうございます！
一箇所スタイルの表記で修正してほしい部分があるので、コメントしました

2022-10-13 07:30 UTC, Hiroya-W commented on ja/source/guide/2.0_python_advanced.rst
> +計算後に引数の <code>state</code> には対応する基底状態が代入されます。
reStructuredtextの場合はバッククォートで囲みます

```suggestion
計算後に引数の ``state`` には対応する基底状態が代入されます。
```

2022-10-14 04:08 UTC, ikanago approved these changes
👍

2022-10-17 08:12 UTC, KowerKoint approved these changes
LGTMです
ついでに聞きたいんですが、apply_to_state()のwork_stateって内部実装みても呼び出し元がわざわざ用意することに意義を感じないんですがどうなんでしょう…(メモリの割当と解放を何度も行うくらいなら同じ場所で計算し続けたほうが多少パフォーマンスが良くなるかもしれないとかそんなところ？)

2022-10-17 09:47 UTC, herring101 commented on ja/source/guide/2.0_python_advanced.rst
> +計算後に引数の <code>state</code> には対応する基底状態が代入されます。
修正しました。
ありがとうございます🙇

2022-10-17 09:55 UTC, merged

2022-10-17 23:42 UTC, forest1040 commented
> apply_to_state()のwork_stateって内部実装みても呼び出し元がわざわざ用意することに意義を感じないんですがどうなんでしょう…(メモリの割当と解放を何度も行うくらいなら同じ場所で計算し続けたほうが多少パフォーマンスが良くなるかもしれないとかそんなところ？)

QuantumStateなので、量子ビット数が大きいと割当、開放も大変なんでしょうね。apply_to_state()内部でwork_stateの割当開放をやると、メモリが足らずに割当失敗したときどうするかとか。。（まぁ、Exception投げるんでしょうけど。）
あとは小さい割当でも数をやるとメモリの断片化ですかね。。