add state tutorial
qulacs/qulacs-rtd pull request #70
Opened 2022-10-25 02:26 UTC by KowerKoint

close #45 
stateサブモジュールのチュートリアルを追加しました。
`partial_trace`、計算内容は英語版Wikipediaを読んで理解したんですが訳語がどこにもなかったので偏トレースと訳して大丈夫そうか要検討です。

https://github.com/qulacs/qulacs/pull/357 で追加した関数の関連の説明は別のPRで追加します

2022-10-25 02:40 UTC, forest1040 commented
@KowerKoint 
`partial_trace`の訳は`部分トレース`かなと思いました。

2022-10-25 02:44 UTC, KowerKoint commented
偏トレースと訳した理由は、「ある次元についてのみ微分を取るpartial derivativeを偏微分と訳すことになっているからある次元についてのトレースを取るpartial traceは偏トレースにしよう」という感じです
部分トレースも候補ではありましたが…

2022-10-25 02:53 UTC, KowerKoint commented
すみません
部分トレースで定着していました……

2022-10-25 03:21 UTC, forest1040 approved these changes
LGTM!

2022-10-25 06:13 UTC, Hiroya-W requested changes
チュートリアル追加、日本語訳の検討ありがとうございます！
コードブロックのスタイルの修正だけお願いします！

2022-10-25 06:13 UTC, Hiroya-W commented on ja/source/guide/2.0_python_advanced.rst
> +   from qulacs import QuantumState
code blockとしてレンダリング出来てないようでした。空白が必要みたいです。

```suggestion
.. code:: python

   from qulacs import QuantumState
```

2022-10-25 06:13 UTC, Hiroya-W commented on ja/source/guide/2.0_python_advanced.rst
> +   from qulacs import QuantumState, DensityMatrix
同じく空白が必要みたいです

```suggestion
.. code:: python

   from qulacs import QuantumState, DensityMatrix
```

2022-10-26 10:24 UTC, herring101 approved these changes
チュートリアル追加ありがとうございます！
個人的にはもう少しコード内にコメントがある方がわかりやすい気がしますが、無いほうがすっきりするかもしれないので今のままでもよさそう。
LGTMです。

2022-10-27 05:04 UTC, Hiroya-W approved these changes
LGTM!

2022-10-31 08:06 UTC, merged